apiVersion: apps/v1
kind: Deployment
metadata:
  name: privideo-backend
  namespace: web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: privideo-backend
  template:
    metadata:
      labels:
        app: privideo-backend
    spec:
      volumes:
        - name: gemini-secret
          secret:
            secretName: gemini-service   # ← 실제 존재하는 secret 이름과 동일해야 함

      containers:
        - name: backend
          image: docker.io/dockdock150/backend:latest
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: myapp-config
            - secretRef:
                name: myapp-secret

          volumeMounts:
            - name: gemini-secret
              mountPath: /var/secrets/google
              readOnly: true

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 15
            failureThreshold: 5
