apiVersion: v1
kind: Service
metadata:
  name: privideo-backend-service
  namespace: cicd
spec:
  type: ClusterIP
  selector:
    app: myapp     # 파드 라벨과 정확히 일치해야 함
  ports:
    - name: http
      port: 8080       # 외부에서 접근할 포트 (cluster 내부에서 사용)
      targetPort: 8080 # Pod 컨테이너 포트
