apiVersion: v1
kind: Service
metadata:
  name: privideo-backend-service
  namespace: cicd
spec:
  type: ClusterIP
  selector:
    app: privideo-backend     
  ports:
    - name: http
      port: 8080       
      targetPort: 8080 
