resources:
  - ../../base

namespace: cicd                # ✅ 실제 배포될 네임스페이스

namePrefix: dev-               # (선택) 리소스 이름 앞에 "dev-" 접두사 추가

images:
  - name: docker.io/dockdock150/backend   # 도커 허브의 실제 이미지 경로
    newTag: "latest"                 # 예: Jenkins가 ${BUILD_NUMBER}로 교체
