apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privideo-backend-ingress
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.privideo.cloud"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Authorization-refresh"
    nginx.ingress.kubernetes.io/cors-expose-headers: "Authorization"
    nginx.ingress.kubernetes.io/cors-max-age: "10"
    
spec:
  ingressClassName: nginx
  rules:
  - host: www.privideo.cloud
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: privideo-backend-service
            port:
              number: 8080

  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: privideo-backend-service
            port:
              number: 8080
              
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privideo-frontend-ingress
  namespace: web
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: privideo-frontend-service
            port:
              number: 80
  - host: www.privideo.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: privideo-frontend-service
            port:
              number: 80
