apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privideo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Backend
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: dev-privideo-backend-service
            port:
              number: 8080
      # Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: privideo-frontend-service
            port:
              number: 80
