global:
  image:
    tag: v2.11.0

  nodeSelector:
    argocd-node: "true"
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "cicd"
      effect: "NoSchedule"

server:
  service:
    type: NodePort
    nodePortHttp: 30122
    servicePortHttp: 80
    targetPort: 8080
  replicas: 1

repoServer:
  replicas: 1

applicationController:
  replicas: 1

redis-ha:
  enabled: false

redis:
  enabled: true

redisSecretInit:
  enabled: true

dex:
  enable: false
