apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: web
data:
  SPRING_PROFILES_ACTIVE: "dev"

  DATASOURCE_URL: "jdbc:postgresql://172.16.2.110:5000/postgres"
  
  REDIS_SENTINEL_HOST: "redis-headless.redis.svc.cluster.local"
  REDIS_SENTINEL_PORT: "26379"
  REDIS_SENTINEL_MASTER: "mymaster"
  REDIS_ACTIVE: "10"
  REDIS_MAX_IDLE: "10"
  REDIS_MIN_IDLE: "2"
  REDIS_TIMEOUT: "3000"

  AWS_REGION: "ap-northeast-2"
  AWS_ORIGINAL_BUCKET: "privideo-original"
  AWS_IMG_BUCKET: "privideo-image"
  AWS_OUTPUT_BUCKET: "privideo-output"
  AWS_UPLOAD_EXPIRATION: "60m"
  
  COOKIE_DOMAIN: ".privideo.cloud"
  CDN_BASE_URL: "stream.privideo.cloud"
  
  JWT_EXCLUDED_PATTERNS: "/user/signup,/user/login,/*/video/airflow/status,/*/video/*/leave"

  GOOGLE_CLOUD_PROJECT_ID: "gen-lang-client-0041043724"
  GOOGLE_CLOUD_LOCATION: "us-central1"
  GEMINI_MODEL_NAME: "gemini-2.0-flash"

  RTZR_BASE_URL: "https://openapi.vito.ai"
  RTZR_CLIENT_ID: "bSV7tYg1y9B5QISrUKJ3"
  
  TOKEN_EXPIRED_IN: "2592000"

  CF_COOKIE_TTL: "7200"
