apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: cicd
data:
  SPRING_PROFILES_ACTIVE: "dev"

  DATASOURCE_URL: "jdbc:postgresql://172.16.2.110:5000/postgres"
  
  REDIS_HOST: "redis"
  REDIS_PORT: "26379"
  REDIS_MASTER: mymaster
  REDIS_ACTIVE: "10"
  REDIS_MAX_IDLE: "10"
  REDIS_MIN_IDLE: "2"
  REDIS_TIMEOUT: "3000"

  AWS_REGION: "ap-northeast-2"
  AWS_ORIGINAL_BUCKET: "privideo-original"
  AWS_IMG_BUCKET: "privideo-image"
  AWS_UPLOAD_EXPIRATION: "60m"

  TOKEN_EXPIRED_IN: "3600"
