apiVersion: v1
kind: Service
metadata:
  name: privideo-frontend-service
spec:
  type: NodePort 
  selector:
    app: privideo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30180  # 외부 접속 포트
      protocol: TCP
