apiVersion: v1
kind: Service
metadata:
  name: privideo-frontend-service
spec:
  type: ClusterIP
  selector:
    app: privideo-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
