apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      nodeSelector:
        cicd: "true"
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "cicd"
          effect: "NoSchedule"

      containers:
        - name: myapp
          image: docker.io/dockdock150/backend:latest
          ports:
            - containerPort: 8080

          # ✅ Readiness Probe
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 25
            periodSeconds: 10
            failureThreshold: 6

          # ✅ Liveness Probe
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 15
            failureThreshold: 5
